trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
  paths:
    exclude:
      - "*.md"
      - .travis.yml
      - appveyor.yml

pr:
  branches:
    include:
      - master
      - develop
      - feature/*

jobs:
- job: windows
  displayName: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 4
    matrix:
      Win32_Debug:
        BuildPlatform: 'Win32'
        Configuration: 'Debug'
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Debug:
        BuildPlatform: 'x64'
        Configuration: 'Debug'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'

  steps:
  - template: ci/azure-pipelines/template.steps.build-unittest.yml

- job: cppcheck
  displayName: 'Windows cppcheck'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 2
    matrix:
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'

  steps:
  - template: ci/azure-pipelines/template.steps.cppcheck.yml

- job: doxygen
  displayName: 'Windows doxygen'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 2
    matrix:
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'

  steps:
  - template: ci/azure-pipelines/template.steps.doxygen.yml

- job: checkEncoding
  displayName: 'Windows checkEncoding'
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - template: ci/azure-pipelines/template.steps.checkEncoding.yml
