steps:
# show environmental variables for debug.
- script: set
  displayName: Show environmental variables for debug

- script: pip install chardet --user
  displayName: install chardet

- script: checkEncoding.bat
  displayName: check encoding
