#############################################################################################################
#   必要な mingw-w64-gcc をインストール手順の 'steps' を定義するテンプレート
#
#   parameters
#       なし
#############################################################################################################
steps:
  - script: echo nothing to do.
    displayName: nothing to do
